# **IMPORT LIBRARIES AND DATA SET**

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

url="https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv"
df=pd.read_csv(url)

df['species'].unique()


array(['setosa', 'versicolor', 'virginica'], dtype=object)

# **EXPLORATORY DATA ANALYSIS**

In [4]:
df.head()


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


## **Label Encoding**

In [6]:
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
df['species']= le.fit_transform(df['species'])

df['species'].unique()

array([0, 1, 2])

# **DATA PREPRATION**

## **Data Seperation and splitting**

In [7]:
y=df["species"]
x=df.drop("species",axis=1)

In [8]:

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

# **Model Building**

## **Logistic Regression**

In [9]:
from sklearn.linear_model import LogisticRegression


lr=LogisticRegression(random_state=0)
lr.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

### **Making prediction**

In [10]:
y_train_lr_pred=lr.predict(x_train)
y_test_lr_pred=lr.predict(x_test)

y_train_lr_pred

array([2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2,
       1, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0,
       1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2,
       0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1,
       0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 2, 0, 1, 2, 2, 0, 1,
       1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

### **Confusion Matrix**

In [23]:
from sklearn import metrics

print(metrics.classification_report(y_train,y_train_lr_pred))
#print(metrics.classification_report(y_test,y_test_lr_pred))

cm_train=metrics.confusion_matrix(y_train,y_train_lr_pred)
cm_test=metrics.confusion_matrix(y_test,y_test_lr_pred)

print(cm_train)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        39
           1       0.97      0.92      0.94        37
           2       0.93      0.98      0.96        44

    accuracy                           0.97       120
   macro avg       0.97      0.97      0.97       120
weighted avg       0.97      0.97      0.97       120

[[39  0  0]
 [ 0 34  3]
 [ 0  1 43]]


### **Accuracy Score**

In [27]:
from sklearn.metrics import accuracy_score

AS_train=accuracy_score(y_train,y_train_lr_pred)
AS_test=accuracy_score(y_test,y_test_lr_pred)
print(AS_test)
print(AS_train)


1.0
0.9666666666666667
